### ISSUE TITLE
Error: regeneratorRuntime is not defined in the lib if I use custom middleware

### ISSUE THREAD

**Issue by keepitsimple** [relay-tools/react-relay-network-modern#28]
I added into my js file
`import 'regenerator-runtime'` 

But as soon as I add a custom middleware I have this error. **If I remove custom middleware from the code it works (I do not have this error).**

```
frontend_1                | /opt/frontend/node_modules/react-relay-network-modern/lib/RelayResponse.js:41
frontend_1                |       var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(res) {
frontend_1                |                                                  ^
frontend_1                | 
frontend_1                | ReferenceError: regeneratorRuntime is not defined
frontend_1                |     at /opt/frontend/node_modules/react-relay-network-modern/lib/RelayResponse.js:41:50
frontend_1                |     at /opt/frontend/node_modules/react-relay-network-modern/lib/RelayResponse.js:94:6
frontend_1                |     at Object.<anonymous> (/opt/frontend/node_modules/react-relay-network-modern/lib/RelayResponse.js:132:2)
frontend_1                |     at Module._compile (module.js:643:30)
frontend_1                |     at Object.Module._extensions..js (module.js:654:10)
frontend_1                |     at Module.load (module.js:556:32)
frontend_1                |     at tryModuleLoad (module.js:499:12)
frontend_1                |     at Function.Module._load (module.js:491:3)
frontend_1                |     at Module.require (module.js:587:17)
frontend_1                |     at require (internal/module.js:11:18)

```

Update:

I found out that if I do not use async I do not have this error.
it works:

```
    next => req => {
      return next(req)
    }
```

it retuns error:

```
    next => async req => {
      const res = await next(req)
      return res
    }
```

**Comment by nodkz** [comment]
Take a look at  https://github.com/relay-tools/react-relay-network-modern#what-if-regeneratorruntime-is-not-defined

Regenerator-runtime should be added to your main (entrypoint) client.js file only once.

**Comment by keepitsimple** [comment]
It's related with babel. There are several ways to solve it presented [here](https://github.com/babel/babel/issues/5085)
